import React from 'react';
import CodePanel from '../../Components/CodePanel';

export default () => {
  return (
    <>
      <section className="accent-bottom panel">
        <h2>Distinct powers</h2>
        <h4>Problem 29</h4>
        <p>
          Consider all integer combinations of aᵇ for 2 ≤ a ≤ 5 and
          2 ≤ b ≤ 5:
        </p>
        <ol className="padded">
          <li>2²=4, 2³=8, 2⁴=16, 2⁵=32</li>
          <li>3²=9, 3³=27, 3⁴=81, 3⁵=243</li>
          <li>4²=16, 4³=64, 4⁴=256, 4⁵=1024</li>
          <li>5²=25, 5³=125, 5⁴=625, 5⁵=3125</li>
        </ol>
        <p>
          If they are then placed in numerical order, with any repeats
          removed, we get the following sequence of 15 distinct terms:
        </p>
        <div className="center">
          4, 8, 9, 16, 25, 27, 32, 64, 81, 125, 243, 256, 625, 1024, 3125
        </div>
        <p>
          How many distinct terms are in the sequence generated by aᵇ for
          2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?
        </p>
      </section>
      <CodePanel title="JavaScript">{`
        m => {
          const sets = [];
        
          for (let i = BigInt(2); i <= m; i++) {
            let power = i;
            for (let j = 2; j <= m; j++) {
              power *= i;
              if (!sets.includes(power)) {
                sets.push(power);
              }
            }
          }
          return sets.length;
        }
    `}</CodePanel>
    </>
  );
};